---
title: "Infonavit"
author: "Jazmín Guadalupe Rodríguez Calderón"
date: "27/1/2021"
output:
  pdf_document:
  toc: TRUE 
toc-title: Contenido 
csl: apa.csl
bibliography: fuentes.bib 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, marning=F, fig.align='right')
```

```{r}
rm(list = ls())

install.packages("pacman")
pacman::p_load(tidyverse,
               foreing,
               kableExtra,
               ggplot2,
               cowplot)

```

```{r}
viviendas<-read.csv("viviendas.csv")
```
\newpage
```{r}
# selección de las variables de interés
Conc <- Conc [ c("folioviv", "foliohog", "ing_cor", "ingtrab", "trabajo", "negocio", "otros_trab", "rentas", "utilidad",
"arrenda", "transfer", "jubilacion", "becas", "donativos", "remesas", "bene_gob", "transf_hog", "trans_inst",
"estim_alqu", "otros_ing","factor","upm","est_dis")]
```


```{r}
Entidades<-c("Estados Unidos Mexicanos", "Aguascalientes", "Baja California", "Baja California Sur",
 "Campeche", "Coahuila de Zaragoza", "Colima", "Chiapas", "Chihuahua", "México", "Durango",
 "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Estado de México", "Michoacán de Ocampo",
 "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí",
 "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz de Ignacio de la Llave", "Yucatán",
 "Zacatecas")
```

